/* linux/arch/arm/mach-s5p6442/mach-apollo.c
 *
 * Copyright (c) 2010 Samsung Electronics Co., Ltd.
 *		http://www.samsung.com/
 *
 * Maintainers: Mark Kennard	<komcomputers@gmail.com>
 *		Miki Dahab	<codermoikop@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
*/

#include <linux/gpio.h>
#include <linux/kernel.h>
#include <linux/types.h>
#include <linux/init.h>
#include <linux/serial_core.h>
#include <linux/i2c.h>

#include <linux/mtd/mtd.h>
#include <linux/mtd/onenand.h>
#include <linux/mtd/partitions.h>
#include <linux/mtd/bml.h>

#include <asm/mach/arch.h>
#include <asm/mach/map.h>
#include <asm/setup.h>
#include <asm/mach-types.h>
#include <asm/hardware/vic.h>

#include <mach/map.h>
#include <mach/regs-clock.h>
#include <mach/regs-gpio.h>

#include <plat/regs-serial.h>
#include <plat/s5p6442.h>
#include <plat/devs.h>
#include <plat/gpio-cfg.h>
#include <plat/cpu.h>
#include <plat/iic.h>
#include <plat/s5p-time.h>
#include <plat/sdhci.h>
#include <plat/onenand-core.h>

#include <media/s5p_fimc.h>

#include <mach/mach-apollo.h>

/* Following are default values for UCON, ULCON and UFCON UART registers */
#define apollo_UCON_DEFAULT	(S3C2410_UCON_TXILEVEL |	\
				 S3C2410_UCON_RXILEVEL |	\
				 S3C2410_UCON_TXIRQMODE |	\
				 S3C2410_UCON_RXIRQMODE |	\
				 S3C2410_UCON_RXFIFO_TOI |	\
				 S3C2443_UCON_RXERR_IRQEN)

#define apollo_ULCON_DEFAULT	S3C2410_LCON_CS8

#define apollo_UFCON_DEFAULT	(S3C2410_UFCON_FIFOMODE |	\
				 S5PV210_UFCON_TXTRIG4 |	\
				 S5PV210_UFCON_RXTRIG4)

static struct s3c2410_uartcfg apollo_uartcfgs[] __initdata = {
	[0] = {
		.hwport		= 0,
		.flags		= 0,
		.ucon		= apollo_UCON_DEFAULT,
		.ulcon		= apollo_ULCON_DEFAULT,
		.ufcon		= apollo_UFCON_DEFAULT,
	},
	[1] = {
		.hwport		= 1,
		.flags		= 0,
		.ucon		= apollo_UCON_DEFAULT,
		.ulcon		= apollo_ULCON_DEFAULT,
		.ufcon		= apollo_UFCON_DEFAULT,
	},
	[2] = {
		.hwport		= 2,
		.flags		= 0,
		.ucon		= apollo_UCON_DEFAULT,
		.ulcon		= apollo_ULCON_DEFAULT,
		.ufcon		= apollo_UFCON_DEFAULT,
	},
};

static struct s3c_sdhci_platdata apollo_hsmmc0_pdata __initdata = {
	.cd_type		= S3C_SDHCI_CD_INTERNAL,
	.clk_type		= S3C_SDHCI_CLK_DIV_INTERNAL,
	.max_width		= 8,
};

static struct s3c_sdhci_platdata apollo_hsmmc1_pdata __initdata = {
	.cd_type		= S3C_SDHCI_CD_INTERNAL,
	.clk_type		= S3C_SDHCI_CLK_DIV_INTERNAL,
	.max_width		= 8,
};

static struct bml_partition apollo_bml_partitions[] = {
	{
		.name		= "kernel",
		.offset		= (40 * SZ_256K),
	}
};

static struct bml_platform_data apollo_bml_pdata = {
	.parts			= apollo_bml_partitions,
	.nr_parts		= ARRAY_SIZE(apollo_bml_partitions),
};

static struct platform_device apollo_bml_device = {
	.name			= "mtd-bml",
	.id			= -1,
	.dev			= {
				.platform_data = &apollo_bml_pdata,
	},
};

static int apollo_hw_rev_pin_value = -1;

static void check_hw_rev_pin(void)
{
	int data;
	apollo_hw_rev_pin_value = 0;

	// set gpio configuration
	s3c_gpio_cfgpin(GPIO_HW_REV_MODE2, GPIO_HW_REV_MODE2_STATE);
	s3c_gpio_cfgpin(GPIO_HW_REV_MODE1, GPIO_HW_REV_MODE1_STATE);
	s3c_gpio_cfgpin(GPIO_HW_REV_MODE0, GPIO_HW_REV_MODE0_STATE);

	data = gpio_get_value(GPIO_HW_REV_MODE2);
	if(data)
		apollo_hw_rev_pin_value |= (0x1<<2);
	data = gpio_get_value(GPIO_HW_REV_MODE1);
	if(data)
		apollo_hw_rev_pin_value |= (0x1<<1);
	data = gpio_get_value(GPIO_HW_REV_MODE0);
	if(data)
		apollo_hw_rev_pin_value |= (0x1<<0);
	
}

int apollo_get_hw_type()
{
	int type;

	switch(apollo_hw_rev_pin_value)
		{
		case 2:		// apollo rev0.4 (memory 4-2-1)
		case 6:		// apollo rev0.5
		case 4:		// apollo rev0.6
		case 5:		// apollo rev0.7
		case 7:		// apollo rev0.9b
			type = 0;
			break;
		case 3:		// apollo OPEN rev0.7
		case 1:		// apollo OPEN rev0.9b
		case 0:		// apollo OPEN rev1.0a
			type = 1;
			break;
		default:
			type = 0;
			break;
		}

	return type;
}
EXPORT_SYMBOL(apollo_get_hw_type);

int apollo_get_remapped_hw_rev_pin()
{
	int revision;

	switch(apollo_hw_rev_pin_value)
		{
		case 2:		// apollo rev0.4 (memory 4-2-1)
			revision = 2;
			break;
		case 6:		// apollo rev0.5
			revision = 3;
			break;
		case 4:		// apollo rev0.6
			revision = 4;
			break;
		case 5:		// apollo rev0.7
			revision = 5;
			break;
		case 7:		// apollo rev0.9b
			revision = 6;
			break;
		case 3:		// apollo OPEN rev0.7
			revision = 5;
			break;
		case 1:		// apollo OPEN rev0.9b
			revision = 6;
			break;
		case 0:		// apollo OPEN rev1.0a
			revision = 7;
			break;
		default:
			revision = 8;
			break;
		}

	return revision;
}

static struct platform_device *apollo_devices[] __initdata = {
	&s3c_device_i2c0,
	&samsung_asoc_dma,
	&s5p6442_device_iis0,
	&s3c_device_wdt,
	&s3c_device_rtc,

	&s3c_device_hsmmc0,
	&s3c_device_hsmmc1,		// SDIO for WLAN

	&s5p_device_fimc0,
	&s5p_device_fimc1,
	&s5p_device_fimc2,
	&s5p_device_jpeg,
	&s3c_device_fb,

	&s5p_device_onenand,
	&apollo_bml_device,
};

static struct i2c_board_info apollo_i2c_devs0[] __initdata = {
	{ I2C_BOARD_INFO("wm8994", 0x1b), },
};

static int s5p6442_gpio_table[][6] = {
	/** OFF PART **/
	/* GPA0 */
	{ GPIO_BT_UART_RXD, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_BT_UART_TXD, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_BT_UART_CTS, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_BT_UART_RTS, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },
	//{ GPIO_AP_COM_RXD, GPIO_AP_COM_RXD_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_DOWN },
	//{ GPIO_AP_COM_TXD, GPIO_AP_COM_TXD_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPA0(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPA0(7), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPA1 */
	{ GPIO_AP_FLM_RXD_2_8V, 2, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_FLM_TXD_2_8V, 2, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },

	/* GPB */
	/* NC */{ S5P6442_GPB(0), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPB(1), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPB(2), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPB(3), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPC0 */
	{ GPIO_CODEC_I2S_CLK, GPIO_CODEC_I2S_CLK_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{ S5P6442_GPC0(1), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CODEC_I2S_WS, GPIO_CODEC_I2S_WS_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CODEC_I2S_DI, GPIO_CODEC_I2S_DI_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_CODEC_I2S_DO, GPIO_CODEC_I2S_DO_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	/* GPC1 */
	/* NC */{S5P6442_GPC1(0), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPC1(1), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPC1(2), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPC1(3), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPC1(4), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	/* GPD0 */
	{ GPIO_VIBTONE_PWM, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPD0(1) , 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPD1 - I2C */
	{ GPIO_CAM_SDA_2_8V, 2, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_SCL_2_8V, 2, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	{ GPIO_AP_SDA_2_8V, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_SCL_2_8V, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },

	{ GPIO_TSP_SDA_2_8V, 2, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_TSP_SCL_2_8V, 2, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },

	/* GPE0 */
	{ GPIO_CAM_PCLK, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_VSYNC, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_HSYNC, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_0, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_1, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_2, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_3, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_4, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPE1 */
	{ GPIO_CAM_D_5, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_6, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_D_7, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_MCLK, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_TOUCH_RST, 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_UP },
	
	/* GPF0 */
	{ GPIO_LCD_HSYNC, GPIO_LCD_HSYNC_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_VSYNC, GPIO_LCD_VSYNC_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_VDEN,   GPIO_LCD_VDEN_STATE,   GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_MCLK,   GPIO_LCD_MCLK_STATE,   GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_0, GPIO_LCD_D_0_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_1, GPIO_LCD_D_1_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPF1 */
	{ GPIO_LCD_D_2, GPIO_LCD_D_2_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_3, GPIO_LCD_D_3_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_4, GPIO_LCD_D_4_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_5, GPIO_LCD_D_5_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_6, GPIO_LCD_D_6_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_7, GPIO_LCD_D_7_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_8, GPIO_LCD_D_8_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_9, GPIO_LCD_D_9_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	/* GPF2 */
	{ GPIO_LCD_D_10, GPIO_LCD_D_10_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_11, GPIO_LCD_D_11_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_12, GPIO_LCD_D_12_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_13, GPIO_LCD_D_13_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_14, GPIO_LCD_D_14_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_15, GPIO_LCD_D_15_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_16, GPIO_LCD_D_16_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_17, GPIO_LCD_D_17_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	 /* GPF3 */
	{ GPIO_LCD_D_18, GPIO_LCD_D_18_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_19, GPIO_LCD_D_19_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_20, GPIO_LCD_D_20_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_21, GPIO_LCD_D_21_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_22, GPIO_LCD_D_22_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_D_23, GPIO_LCD_D_23_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	/* GPG0 */
	{ GPIO_CAM_EN, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPG0(1), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_TOUCH_INT, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_3M_nSTBY, GPIO_CAM_3M_nSTBY_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPG0(4), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	{GPIO_UART_SEL, 1, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE }, // check
	/* NC */{S5P6442_GPG0(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* GPG1 */
	{ GPIO_WLAN_SDIO_CLK, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_DOWN },
	{ GPIO_WLAN_SDIO_CMD, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_nRST, GPIO_WLAN_nRST_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_SDIO_D_0, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_SDIO_D_1, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_SDIO_D_2, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_SDIO_D_3, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },

	/* GPG2 */
	{ GPIO_T_FLASH_CLK, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_T_FLASH_CMD, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPG2(2), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_T_FLASH_D_0, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },	
	{ GPIO_T_FLASH_D_1, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_T_FLASH_D_2, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_T_FLASH_D_3, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/*GPJ0 */ 
	{ GPIO_KEY_COL0, GPIO_KEY_COL0_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	{ GPIO_KEY_COL1, GPIO_KEY_COL1_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	{ GPIO_KEY_COL2, GPIO_KEY_COL2_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	{ GPIO_KEY_COL3, GPIO_KEY_COL3_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	{ GPIO_FM_SCL_2_8V, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_FM_SDA_2_8V, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ0(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ0(7), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
      
	/*GPJ1 */  
	{ GPIO_PHONE_ON, GPIO_PHONE_ON_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_HAPTIC_EN, GPIO_HAPTIC_EN_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	/* NC */{S5P6442_GPJ1(2), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ1(3), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ1(4), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_CAM_3M_nRST, GPIO_CAM_3M_nRST_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	
	/*GPJ2 */
	{ GPIO_CODEX_XTAL_EN, 0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{GPIO_MICBIAS2_EN, 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_PREV, S3C_GPIO_PULL_NONE },
	/* TP */{ GPIO_TA_CURRENT_SEL_AP, 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_FM_INT, GPIO_FM_INT_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_UP },
	{ GPIO_FM_BUS_nRST, GPIO_FM_BUS_nRST_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_UP },
	{ GPIO_BT_WAKE, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_WLAN_WAKE, GPIO_WLAN_WAKE_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/*GPJ3 */
	{ GPIO_WLAN_BT_EN, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE},
	{GPIO_MIC_SEL, 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_PREV, S3C_GPIO_PULL_NONE },
	{ GPIO_EAR_SEL, GPIO_EAR_SEL_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_PREV, S3C_GPIO_PULL_NONE}, 
	{ GPIO_BOOT_MODE, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
//	{ GPIO_PS_OUT, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
//	{ GPIO_PS_EN, GPIO_PS_EN_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },
//  { GPIO_SENSOR_SDA, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
//	{ GPIO_SENSOR_SCL, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_GPJ3(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_BT_nRST, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
#ifdef USE_GPIO_ENABLE_FOR_LCD_POWER
	{ GPIO_TOUCH_EN, 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },
	{ GPIO_ALS_nRST, GPIO_ALS_nRST_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
#endif

	/* GPJ4 */
	{ GPIO_AP_PMIC_SDA, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ4(1), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_GPJ4(2), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_PMIC_SCL, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_MSENSE_nRST, GPIO_MSENSE_nRST_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },

	/* MP0_1 */
	{ GPIO_DISPLAY_CS, GPIO_DISPLAY_CS_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_NANDCS, GPIO_AP_NANDCS_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP01(3), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP01(4), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP01(5), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP01(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP01(7), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

	/* MP0_3 */
//	/* NC */{S5P6442_MP03(2), 1, GPIO_LEVEL_HIGH, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE },

	/* MP0_4 */
//	/* NC */{S5P6442_MP04(0), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_DISPLAY_CLK, GPIO_DISPLAY_CLK_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_DISPLAY_SI, GPIO_DISPLAY_SI_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_LCD_ID, GPIO_LCD_ID_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_DOWN, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP04(5), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
//	/* NC */{S5P6442_MP04(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_HW_REV_MODE0, GPIO_HW_REV_MODE0_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	
	/* MP0_5 */
	{ GPIO_HW_REV_MODE1, GPIO_HW_REV_MODE1_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_HW_REV_MODE2, GPIO_HW_REV_MODE2_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_SCL, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	{ GPIO_AP_SDA, 0, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_MP05(4), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	{ GPIO_MLCD_RST, GPIO_MLCD_RST_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
	/* NC */{S5P6442_MP05(6), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_UP },
	/* NC */{S5P6442_MP05(7), 1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },

//	{ GPIO_USB_SEL30, GPIO_USB_SEL30_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
#ifdef USE_GPIO_ENABLE_FOR_LCD_POWER
//	{ GPIO_MLCD_ON, GPIO_MLCD_ON_STATE, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_NONE },
#endif
//	{ GPIO_ADC_EN, GPIO_ADC_EN_STATE, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE, S3C_GPIO_PULL_UP, S3C_GPIO_PULL_DOWN },

};

static int s5p6442_gpio_alive_table[][4] = {
/********************************* ALIVE PART ************************************************/
	/* GPH0 */
	{ GPIO_AP_PS_HOLD, 0x3, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_ACC_INT, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_DOWN},
	{ GPIO_BUCK_1_EN_A, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_BUCK_1_EN_B, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_BUCK_2_EN, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_FLM_SEL, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_EARJACK_DET, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_AP_PMIC_IRQ, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},

	/* GPH1 */
	{ GPIO_SIM_nDETECT, 0xf, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE},
	{ GPIO_CP_RST, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_UP},
	{ GPIO_PDA_ACTIVE, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE}, 
	{ GPIO_nINT_ONEDRAM_AP, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_RESET_REQ_N, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_DOWN},
	//{ GPIO_CODEC_LDO_EN, 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ S5P6442_GPH1(6), 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE}, 	
	{ GPIO_PHONE_ACTIVE, 0xf, GPIO_LEVEL_NONE, S3C_GPIO_PULL_NONE},

	/* GPH2 */
	{ GPIO_T_FLASH_DETECT, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_MSENSE_IRQ, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_DOWN},
	{ GPIO_EAR_SEND_END, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ S5P6442_GPH2(3), 0x1, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	//{ GPIO_WLAN_HOST_WAKE, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	//{ GPIO_BT_HOST_WAKE, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_nPOWER, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_JACK_nINT, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},

	/* GPH3 */
	{ GPIO_KEY_ROW0, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},  // OK
	{ GPIO_PS_OUT, 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},
	{ GPIO_KEY_ROW2, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_UP},  // CAPTURE
	{ GPIO_KEY_ROW3, 0x0, GPIO_LEVEL_LOW, S3C_GPIO_PULL_UP},  // NC
	{ S5P6442_GPH3(4), 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},  // VOL_UP
	{ S5P6442_GPH3(5), 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},  // VOL_DOWN
	{ S5P6442_GPH3(6), 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},  // BACK
	{ S5P6442_GPH3(7), 0xf, GPIO_LEVEL_LOW, S3C_GPIO_PULL_NONE},  // MENU

};

void s5p_config_gpio_alive_table(int array_size, int (*gpio_table)[4])
{
	u32 i, gpio;

	pr_debug("%s: ++\n", __func__);

	for (i = 0; i < array_size; i++) {
		gpio = gpio_table[i][0];
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(gpio_table[i][1]));
		s3c_gpio_setpull(gpio, gpio_table[i][3]);
		if (gpio_table[i][2] != GPIO_LEVEL_NONE)
			gpio_set_value(gpio, gpio_table[i][2]);
		}
	pr_debug("%s: --\n", __func__);
}
EXPORT_SYMBOL(s5p_config_gpio_alive_table);

void s5p_config_gpio_table(int array_size, int (*gpio_table)[6])
{
	u32 i, gpio;

	pr_debug("%s: ++\n", __func__);
	for (i = 0; i < array_size; i++) {
		gpio = gpio_table[i][0];		
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(gpio_table[i][1]));
		s3c_gpio_setpull(gpio, gpio_table[i][3]);
		s3c_gpio_cfgpin(gpio, gpio_table[i][4]);
		s3c_gpio_setpull(gpio, gpio_table[i][5]);
		if (gpio_table[i][2] != GPIO_LEVEL_NONE)
			gpio_set_value(gpio, gpio_table[i][2]);
	}

	if(apollo_get_remapped_hw_rev_pin()<=4)
	{		
		gpio = S5P6442_GPJ3(5);		
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(1));
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_DOWN);
		s3c_gpio_cfgpin(gpio, S3C_GPIO_PULL_DOWN);
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);	
		
		gpio = S5P6442_GPJ3(6);		
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(1));
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(gpio, S3C_GPIO_PULL_NONE);
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);
		gpio_set_value(gpio, GPIO_LEVEL_LOW);	
	}
	else
	{
		gpio = S5P6442_GPJ3(5);		
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(0));
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(gpio, S3C_GPIO_PULL_UP);
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);	
		
		gpio = S5P6442_GPJ3(6);		
		s3c_gpio_cfgpin(gpio, S3C_GPIO_SFN(0));
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);
		s3c_gpio_cfgpin(gpio, S3C_GPIO_PULL_UP);
		s3c_gpio_setpull(gpio, S3C_GPIO_PULL_NONE);			
	}

	pr_debug("%s: --\n", __func__);
}
EXPORT_SYMBOL(s5p_config_gpio_table);

void s5p6442_init_gpio(void)
{
	s5p_config_gpio_table(ARRAY_SIZE(s5p6442_gpio_table),
			s5p6442_gpio_table);

	__raw_writel(0x00, (S5P6442_GPA0_BASE + 0x2d0));  // for reducing sleep current (MP0_2)	// 20101014 0x20 > 0x00
	__raw_writel(0x90, (S5P6442_GPA0_BASE + 0x2f0));  // for reducing sleep current (MP0_3)	// 20101014 0x290 > 0x90

	s5p_config_gpio_alive_table(ARRAY_SIZE(s5p6442_gpio_alive_table),
					s5p6442_gpio_alive_table);
}

static void __init apollo_map_io(void)
{
	s5p_init_io(NULL, 0, S5P_VA_CHIPID);
	s3c24xx_init_clocks(12000000);
	s3c24xx_init_uarts(apollo_uartcfgs, ARRAY_SIZE(apollo_uartcfgs));
	s5p_set_timer_source(S5P_PWM3, S5P_PWM4);
}

static void __init apollo_machine_init(void)
{
	check_hw_rev_pin();
	s5p6442_init_gpio();
	s3c_i2c0_set_platdata(NULL);
	i2c_register_board_info(0, apollo_i2c_devs0,
			ARRAY_SIZE(apollo_i2c_devs0));
	platform_add_devices(apollo_devices, ARRAY_SIZE(apollo_devices));

	s3c_sdhci0_set_platdata(&apollo_hsmmc0_pdata);
	s3c_sdhci1_set_platdata(&apollo_hsmmc1_pdata);

	printk("%s : hw_rev_pin=0x%x\n", __func__, apollo_hw_rev_pin_value);
	printk("%s : bootmode=0x%x\n", __func__, gpio_get_value(GPIO_BOOT_MODE));
}

static void __init apollo_fixup(struct tag *tags, char **cmdline,
	struct meminfo *mi)
{
	mi->nr_banks = 2;
	mi->bank[0].start = PHYS_OFFSET;
	mi->bank[0].size = PHYS_SIZE_DDR;

	mi->bank[1].start = PHYS_OFFSET_ONEDRAM;
	mi->bank[1].size = PHYS_SIZE_ONEDRAM;
}

MACHINE_START(APOLLO, "APOLLO")
	.atag_offset	= 0x100,

	.fixup		= apollo_fixup,

	.init_irq	= s5p6442_init_irq,
	.handle_irq	= vic_handle_irq,
	.map_io		= apollo_map_io,
	.init_machine	= apollo_machine_init,
	.timer		= &s5p_timer,
MACHINE_END

